[project]
name = "terdious"
version = "0.1.0"
description = "Tired of tedious debugging sessions? Make them terdious!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.27.1",
    "rich>=14.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
